pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building your application..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing your application..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying your application....'
                echo 'Jenkins running in deployed section....'
            }
        }
    }
}
